x=float(input("Ingrese el valor de x : "))
y=float(input("Ingrese el valor de y : "))
z=float(input("Ingrese el valor de z : "))
m=float
m=(x +(y/z))/(x- (y/z))
print(" El valor de x es: \n x={0}\n".format(x))
print(" El valor de y es: \n y={0}\n".format(y))
print(" El valor de z es: \n z={0}\n".format(z))
print(" El valor de m es: \n m={0}\n".format(m))